// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,long_type_string,client_grpc1
// @generated from protobuf file "authzed/api/materialize/v0/relationships.proto" (package "authzed.api.materialize.v0", syntax proto3)
// tslint:disable
import { RelationshipsService } from "./relationships.js";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { ExperimentalCountRelationshipsByFilterResponse } from "./relationships.js";
import type { ExperimentalCountRelationshipsByFilterRequest } from "./relationships.js";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service authzed.api.materialize.v0.RelationshipsService
 */
export interface IRelationshipsServiceClient {
    /**
     * EXPERIMENTAL: CountRelationships returns the count of relationships for a given filter.
     *
     * @generated from protobuf rpc: ExperimentalCountRelationshipsByFilter(authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterRequest) returns (authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterResponse);
     */
    experimentalCountRelationshipsByFilter(input: ExperimentalCountRelationshipsByFilterRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ExperimentalCountRelationshipsByFilterResponse) => void): grpc.ClientUnaryCall;
    experimentalCountRelationshipsByFilter(input: ExperimentalCountRelationshipsByFilterRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: ExperimentalCountRelationshipsByFilterResponse) => void): grpc.ClientUnaryCall;
    experimentalCountRelationshipsByFilter(input: ExperimentalCountRelationshipsByFilterRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ExperimentalCountRelationshipsByFilterResponse) => void): grpc.ClientUnaryCall;
    experimentalCountRelationshipsByFilter(input: ExperimentalCountRelationshipsByFilterRequest, callback: (err: grpc.ServiceError | null, value?: ExperimentalCountRelationshipsByFilterResponse) => void): grpc.ClientUnaryCall;
}
/**
 * @generated from protobuf service authzed.api.materialize.v0.RelationshipsService
 */
export class RelationshipsServiceClient extends grpc.Client implements IRelationshipsServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * EXPERIMENTAL: CountRelationships returns the count of relationships for a given filter.
     *
     * @generated from protobuf rpc: ExperimentalCountRelationshipsByFilter(authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterRequest) returns (authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterResponse);
     */
    experimentalCountRelationshipsByFilter(input: ExperimentalCountRelationshipsByFilterRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ExperimentalCountRelationshipsByFilterResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ExperimentalCountRelationshipsByFilterResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: ExperimentalCountRelationshipsByFilterResponse) => void)): grpc.ClientUnaryCall {
        const method = RelationshipsService.methods[0];
        return this.makeUnaryRequest<ExperimentalCountRelationshipsByFilterRequest, ExperimentalCountRelationshipsByFilterResponse>(`/${RelationshipsService.typeName}/${method.name}`, (value: ExperimentalCountRelationshipsByFilterRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): ExperimentalCountRelationshipsByFilterResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
