// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,long_type_string,client_grpc1
// @generated from protobuf file "authzed/api/materialize/v0/relationships.proto" (package "authzed.api.materialize.v0", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ZedToken } from "../../v1/core.js";
import { RelationshipFilter } from "../../v1/permission_service.js";
/**
 * @generated from protobuf message authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterRequest
 */
export interface ExperimentalCountRelationshipsByFilterRequest {
    /**
     * relationship_filter specifies the filter to apply when counting relationships.
     *
     * @generated from protobuf field: authzed.api.v1.RelationshipFilter relationship_filter = 1;
     */
    relationshipFilter?: RelationshipFilter;
}
/**
 * @generated from protobuf message authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterResponse
 */
export interface ExperimentalCountRelationshipsByFilterResponse {
    /**
     * relationship_count is the count of relationships that match the filter.
     *
     * @generated from protobuf field: uint64 relationship_count = 1;
     */
    relationshipCount: string;
    /**
     * read_at is the ZedToken at which the relationship count applies.
     *
     * @generated from protobuf field: authzed.api.v1.ZedToken read_at = 2;
     */
    readAt?: ZedToken;
}
// @generated message type with reflection information, may provide speed optimized methods
class ExperimentalCountRelationshipsByFilterRequest$Type extends MessageType<ExperimentalCountRelationshipsByFilterRequest> {
    constructor() {
        super("authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterRequest", [
            { no: 1, name: "relationship_filter", kind: "message", T: () => RelationshipFilter, options: { "buf.validate.field": { required: true }, "validate.rules": { message: { required: true } } } }
        ]);
    }
    create(value?: PartialMessage<ExperimentalCountRelationshipsByFilterRequest>): ExperimentalCountRelationshipsByFilterRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ExperimentalCountRelationshipsByFilterRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExperimentalCountRelationshipsByFilterRequest): ExperimentalCountRelationshipsByFilterRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* authzed.api.v1.RelationshipFilter relationship_filter */ 1:
                    message.relationshipFilter = RelationshipFilter.internalBinaryRead(reader, reader.uint32(), options, message.relationshipFilter);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExperimentalCountRelationshipsByFilterRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* authzed.api.v1.RelationshipFilter relationship_filter = 1; */
        if (message.relationshipFilter)
            RelationshipFilter.internalBinaryWrite(message.relationshipFilter, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterRequest
 */
export const ExperimentalCountRelationshipsByFilterRequest = new ExperimentalCountRelationshipsByFilterRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ExperimentalCountRelationshipsByFilterResponse$Type extends MessageType<ExperimentalCountRelationshipsByFilterResponse> {
    constructor() {
        super("authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterResponse", [
            { no: 1, name: "relationship_count", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "read_at", kind: "message", T: () => ZedToken, options: { "buf.validate.field": { required: true }, "validate.rules": { message: { required: true } } } }
        ]);
    }
    create(value?: PartialMessage<ExperimentalCountRelationshipsByFilterResponse>): ExperimentalCountRelationshipsByFilterResponse {
        const message = { relationshipCount: "0" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ExperimentalCountRelationshipsByFilterResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExperimentalCountRelationshipsByFilterResponse): ExperimentalCountRelationshipsByFilterResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 relationship_count */ 1:
                    message.relationshipCount = reader.uint64().toString();
                    break;
                case /* authzed.api.v1.ZedToken read_at */ 2:
                    message.readAt = ZedToken.internalBinaryRead(reader, reader.uint32(), options, message.readAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExperimentalCountRelationshipsByFilterResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 relationship_count = 1; */
        if (message.relationshipCount !== "0")
            writer.tag(1, WireType.Varint).uint64(message.relationshipCount);
        /* authzed.api.v1.ZedToken read_at = 2; */
        if (message.readAt)
            ZedToken.internalBinaryWrite(message.readAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message authzed.api.materialize.v0.ExperimentalCountRelationshipsByFilterResponse
 */
export const ExperimentalCountRelationshipsByFilterResponse = new ExperimentalCountRelationshipsByFilterResponse$Type();
/**
 * @generated ServiceType for protobuf service authzed.api.materialize.v0.RelationshipsService
 */
export const RelationshipsService = new ServiceType("authzed.api.materialize.v0.RelationshipsService", [
    { name: "ExperimentalCountRelationshipsByFilter", options: {}, I: ExperimentalCountRelationshipsByFilterRequest, O: ExperimentalCountRelationshipsByFilterResponse }
]);
